version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: test_case
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_case"]
      interval: 5s
      timeout: 5s
      retries: 10

  fake-service:
    build: .
    command: >
      sh -c "uvicorn fake_service:fake_service --host 0.0.0.0 --port 8001"
    environment:
      FAKE_SERVICE_URL: http://fake-service:8001
    ports:
      - "8001:8001"
    depends_on:
      - db

  api:
    build: .
    command: >
      sh -c "
      python - <<'PY'
      import asyncio
      from app.init_db import init_db
      asyncio.run(init_db())
      PY
      uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      DSN: postgresql://postgres:postgres@db:5432/test_case
      FAKE_SERVICE_URL: http://fake-service:8001
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      fake-service:
        condition: service_started

volumes:
  pgdata:
